version: '3'
services:
  gateway:
    build: gateway
    image: chgivan/micro/gateway:latest
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front-net
    deploy:
      restart_policy:
        condition: on-failure
  comments:
    build: comments
    image: chgivan/micro/comment
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ=rabbitmq
      - DB_HOST=mongodb
    networks:
      - front-net
      - back-net
  articles:
    build: articles
    image: chgivan/micro/articles:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ=rabbitmq
      - DB_HOST=mongodb
    networks:
      - front-net
      - back-net
  users:
    build: users
    image: chgivan/micro/users:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ=rabbitmq
      - DB_HOST=userdb
      - DB_PASSWORD=123456
      - DB_DATABASE=usersDB
      - DB_USER=my_user
    networks:
      - front-net
      - back-net
  userdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=my_user
      - POSTGRES_DB=usersDB
    networks:
      - back-net
  rabbitmq:
    image: "rabbitmq"
    networks:
      - back-net
  mongodb:
    image: "mongo"
    networks:
      - back-net
networks:
  front-net:
  back-net:
