version: '3'
services:
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  mongod:
    image: "mongo"
    ports:
      - "27017:27017"
